dist: trusty
cache: bundler
language: ruby
os: osx

rvm:
  - 2.5.0

services:
  - mysql

before_install:
- gem install rails -v 5.1.5

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - rails test